### ISSUE TITLE
Is it possible to generate XID from SQL?

### ISSUE THREAD

**Issue by derkan** [rs/xid#52]
Hi,
To set `DEFAULT` value for an `PK` of table, I wonder if has anyone tried to generate a valid `xid` value by using SQL.

For example for UUIDv4, we can [generate default value](https://stackoverflow.com/questions/12505158/generating-a-uuid-in-postgres-for-insert-statement) if `uuid-ossp` extension is not installed for PostrgreSQL as:

```sql
`CREATE TABLE IF NOT EXISTS table (
   id VARCHAR(36) DEFAULT md5(random()::text || clock_timestamp()::text)::uuid  NOT NULL,
....
```
Of course it'll be better to generate from application but, I it makes simpler to add default value for manual interactions with tables.

Has anyone tried to develop an SQL function to geneate `xid`?

**Comment by jonagoldman** [comment]
Looking for the same thing. Would like to use XID instead of UUID as default values in SQL/MySQL.
I see there is some code related to SQL already in the package, anyone can help?

**Comment by rs** [comment]
You could possibly port the algorithm into a UDF.

**Comment by jonagoldman** [comment]
@rs I think it should be possible, but I'm not the correct person to do it :)

I guess my question was, how people are using XID with relational databases?

Given the fact that relational databases are pretty common, I guessed someone already stumbled upon the need to create XIDs in raw SQL. For example to insert 1000 records in a single query without the need to generate 1000 XIDs in a loop first.

**Comment by rs** [comment]
What is the problem of generating them on the client?

**Comment by jonagoldman** [comment]
It's totally fine for simple things like an ``insert``:
```sql
insert into table (xid, other, ...) values ('9m4e2mr0ui3e8a215n4g', 'hello' ,...), ...
```
But for any other type of query, this approach will not work.

If you need ``insert select`` to copy, duplicate or make calculations, you need to generate them in SQL:

```sql
insert into table_2 (xid, calc, ...) select 'dynamic_xid_needed_here' as xid, calc * 1 as calc from table_1
```

or you need a ``recursive cte`` to generate a series of dates:
```sql
with recursive series (xid, date) as (
    select 'dynamic_xid_needed_here' as xid, date
    union
    select xid, date + interval 1 day as date
    # ...
) 
```
or you need to work with large amounts of data.

Basically if you want to take advantage of the SQL language, you need a way to generate XIDs in SQL.
Otherwise you must give up on 90% of the power of the language, and you are restricted to the basics.

**Comment by derkan** [comment]
Hi, 
I've found [this repo](https://github.com/iCyberon/pg_xid) for PostgreSQL. It is an extension which generates `xid` for PostgreSQL. For newer versions it was failing to load, I [patched it for random generator](https://github.com/derkan/pg_xid/tree/newrandom) and generated xid from SQL:

```sql
testdb=# SELECT encode(xid(),'hex');
          encode
--------------------------
 5f0068f7f01d6b081d52b222
(1 row)
```
And converted this `hex` value to `base32` and trimmed `===` and tried to load in `xid` with the following code. 

```go
package main

import(
        "fmt"
        "os"
        "strings"
        "github.com/rs/xid"
        "encoding/hex"
        "encoding/base32"
)

func main() {
        pgHex := "5f0068f7f01d6b081d52b222"
        pgBin, err := hex.DecodeString(pgHex)
        if err != nil {
                fmt.Printf("Failed to decode, err: %v\n", err)
                os.Exit(1)
        }
        str32 := strings.ToLower(strings.TrimRight(base32.StdEncoding.EncodeToString(pgBin),"="))
        guid, err := xid.FromString(str32)
        if err != nil {
                fmt.Printf("Failed to parse: %s, err: %v\n", str32, err)
                os.Exit(1)
        }
        println(guid.String())
}
```

Unfortunately loading failed:

```bash
erkan@DERKAN:xid> go run main.go
Failed to parse: l4agr57qdvvqqhkswira , err: xid: invalid ID
exit status 1
```

Can anyone spot compatibility issue here?

**Comment by jonagoldman** [comment]
I have no experience with Go or C so maybe I'm missing something,
but reading how an XID is generated I don't see any crazy thing that will require extending SQL.

It is similar to UUID so it might be possible to generate a [uuid](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid) and then extract the timestamp, mac address, random and counter.

It is possible to get the parts individually:

- 4-byte value representing the seconds since the Unix epoch
  - **[unix_timestamp()](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp)**
- 3-byte machine identifier
  - **[server_uuid](https://dev.mysql.com/doc/refman/8.0/en/replication-options.html#sysvar_server_uuid)**
- 2-byte process id
  -  `show full processlist;` query or **[connection_id()](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_connection-id)**
- 3-byte counter, starting with a random value
  - this can be achieved using a variable or similar

But this is just a thought I'm not familiar with unique id generation.

**Comment by BrianLeishman** [comment]
You can actually create MySQL UDFs in Golang! https://github.com/StirlingMarketingGroup/mysql-xid

# Usage

### `xid_bin`

Returns a new xid in the 12 byte binary version. Sadly this couldn't be called simply "xid", because I guess MySQL already has a native function with that name that is unrelated to this.

```sql
`xid` ( ) : binary(12)
```
---
### `xid_string`

Returns a new xid in the 20 char, base32 version (`[0-9a-v]{20}`).

```sql
`xid_string` ( ) : char(20)
```
---
### `xid_to_bin`

Takes an encoded xid and returns the binary version. Will return `null` if the value given was not a valid xid.

```sql
`xid_to_bin` ( char(20) `id` ) : binary(12)
```
### `bin_to_xid`

Takes an binary xid and returns the encoded version. Will return `null` if the value given was not a valid xid.

```sql
`bin_to_xid` ( binary(12) `id` ) : char(20)
```
---
## Examples

```sql
select`xid_bin`();
-- 0x604B7B580C43999B8B09D268

select`xid_string`();
-- 'c15nmq0c8ecpn2o9q9kg'

select`bin_to_xid`(0x604B7B580C43999B8B09D268);
-- 'c15nmm0c8ecpn2o9q9k0'
select`bin_to_xid`(null);
-- null
select`bin_to_xid`('yeet');
-- notice how xid doesn't throw errors for this input!
-- 'f5imat00000000000000'

select`xid_to_bin`('c15nmq0c8ecpn2o9q9kg');
-- 0x604B7B680C43999B8B09D269
select`xid_to_bin`(null);
-- null
select`xid_to_bin`('yeet');
-- null
select`xid_to_bin`('123abc');
-- null
```
---

**Comment by derkan** [comment]
I've found an  xid extension for postgresql [here](https://github.com/iCyberon/pg_xid).
Thanks for all answers.
